# Page settings
baseurl = "www.hcdz-hr.com"
title = "南京汇诚鼎智企业管理咨询有限公司"
languageCode = "zh-CN"
theme = "hugo-elate-theme"

[params]
  
  staticDir = ["static"]
  # custom_css = ["css/custom1.css", "css/custom2.css"]
  custom_css = ["css/custom.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "汇诚鼎智"
    home = "主页"
    services = "产品中心"
    testimonials = "典型案例"
    work = "公司动态"
    about = "核心团队"
    contact = "联系我们"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "致力于专业的人力资源管理咨询服务"
    subtitle = '企业愿景：助力中小企业成长，成就行业领袖品牌<br/> 企业使命：全面打造专业的跨组织共享HR中心&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/> 企业目标：帮助中小企业节约管理成本，提升效率'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "公司简介"
    description = "南京汇诚鼎智企业管理咨询有限公司是一家聚焦于深度解决企业人力资源管理问题的公司。“共享HR中心”是汇诚鼎智的重点项目，旨在全面打造专业的跨组织共享HR中心。该项目致力于突破资源壁垒，在人力资源管理专业领域实现知识、经验和服务的多层次整合与共享。汇诚鼎智对不同客户群体均具备透彻的专业分析能力，提供个性化订制和多种组合解决方案，充分满足企业持续发展的需求。<br/><br/>"
    url = "#"
    # button = "Get In Touch"
    icon = "icon-home"
    # img = "img_10.jpg"

  [[params.intro.item]]
    title = "服务理念"
    description = "企业的成长依托于人力资源的引导和开发。我们深知，有效的人力资源管理需要具备“顶天”（满足企业战略发展需要）和“立地”（符合管理现实，可以落地执行）的特点。我们的方案是在行业专家和专业团队通力合作下真正解决企业在不同发展阶段的人力资源管理遇到的问题。通过实用规范的方法激活企业内部人才能量、整合内外部协同资源、放大企业发展想象空间为前提条件，实现稳定的内部管理支撑力，为企业构建具有逻辑性、时空性、传承性的企业文化。"
    url = "#"
    # button = "Click Me"
    icon = "icon-briefcase"
    # img = "img_10.jpg"

  [[params.intro.item]]
    title = "我们的优势"
    description = "① 人力资源行业二十几年丰富经验的专业学术及实战核心团队会诊；<br/>② 100%量身为企业定制适用于3-5年的全套的人力资源管理支撑方案；<br/> ③ 专长于团队正向激励、团队效能提升、企业文化传承，所涉案例基本达成率100%；<br/> ④ 为企业节约60%-90%的时间成本和40%-60%的人力成本；<br/> ⑤ 制造业、互联网、快消等多行业丰富项目管理和集团式人力体系构建、重建、二次开发经验和成功案例。"
    url = "#"
    # button = "Why us?"
    icon = "icon-check"
    # img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Services section
  [params.services]
    enable = true
    title = "产品中心"
    description = "针对企业在不同发展阶段的个性化需求，推出差异化的产品方案，提供覆盖人力资源各个模块、流程和细节的规范服务。"

    [[params.services.item]]
      title = "卓越定制"
      description = "为企业量身定制人力资源管理整体或各模块（如绩效、培训等）的深层解决方案，并有计划地落地执行 <br/> 适用于希望深度改造人力资源管理现状、显著提高现有人员专业能力与素养的企业"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "HR管家"
      description = "帮助企业快速建立规范化、流程化和细节化的基础人力资源体系（包括制度制定及各模块建设等），并有计划地落地执行 <br/>适用于人员管理跟不上业务发展节奏、需要尽快完成基础人力资源管理建设并投入使用的成长型企业 "
      icon = "icon-layers2"

    [[params.services.item]]
      title = "蜜蜂服务"
      description = "为多家企业协理人力资源管理中的基础事项，减轻企业事务负担 <br/> 适用于园区、孵化器、协会、联盟等大客户"
      icon = "icon-video2"

      [[params.services.item]]
      title = "咨询服务"
      description = "为企业提供人力资源管理问题的全面解答与建议 <br/> 适用于所有希望提升人力资源管理质量及效率的企业"
      icon = "icon-monitor"


  # Work section
  [params.work]
    enable = true
    title = "公司动态"
    description = ""
    footertext = ''

    [[params.work.row]]
      img = "1.jpg"
      alt = "Image2"
      title = ""
      subtitle = "某交通科技公司培训现场"

    [[params.work.row]]
      img = "2.jpg"
      alt = "Image2"
      title = ""
      subtitle = "某软件公司人才发展项目研讨"

    [[params.work.row]]
      img = "3.jpg"
      alt = "Image3"
      title = ""
      subtitle = "南京市中小企业协会会员代表大会"

    [[params.work.row]]
      img = "4.jpg"
      alt = "Image4"
      title = ""
      subtitle = "某信息技术公司项目沟通现场"

    [[params.work.row]]
      img = "5.jpg"
      alt = "Image5"
      title = ""
      subtitle = "南京大学MBA实训基地揭牌仪式"

    [[params.work.row]]
      img = "6.jpg"
      alt = "Image6"
      title = ""
      subtitle = "某交通集团项目需求调研会"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "典型案例"
    description = ""

    [[params.testimonials.item]]
      quote = '
1.&nbsp;公司基础架构及岗位配置<br/>
2.&nbsp;HR基础制度量身设计<br/>
3.&nbsp;人才的选用和激励体系<br/>
4.&nbsp;培训体系建设及好习惯培养<br/>
5.&nbsp;业务管理及实施工具<br/>
6.&nbsp;日常管理问题的咨询建议<br/>
7.&nbsp;员工关系管理<br/>
8.&nbsp;劳动风险规避管理<br/>
'
      person = '某科技公司HR基础运行体系设计&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/><span class="subtext">服务周期：3+9</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = '
1.&nbsp;高绩效管理团队的建设<br/>
2.&nbsp;业绩翻番团队的打造<br/>
3.&nbsp;营销团队的商务礼仪<br/>
4.&nbsp;HR规划对企业发展的帮助<br/>
5.&nbsp;招聘原来不简单<br/>
6.&nbsp;溶于血脉的企业文化打造<br/>
7.&nbsp;员工激励的有效组合拳<br/>
8.&nbsp;如何做好人才梯队建设<br/>
'
      person = '某行业协会管理培训课程开发&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/><span class="subtext">服务周期：12</span>'
      img = "person2.jpg"
      alt = "Person2"
      
    [[params.testimonials.item]]
      quote = '
1.&nbsp;如何培养、留住骨干？<br/>
2.&nbsp;关于“空降兵”<br/>
3.&nbsp;老板在公司能交几个朋友<br/>
4.&nbsp;老板当场做决定更体现效率<br/>
5.&nbsp;股份制，分红与年终奖<br/>
6.&nbsp;公司的变革？<br/>
7.&nbsp;大树底下好乘凉<br/>
8.&nbsp;人尽其才，物尽其用<br/>
'
      person = '某交通集团BOSS私教中高级辅导课程<br/><span class="subtext">服务周期：12</span>'
      img = "person3.jpg"
      alt = "Person3"

    [[params.testimonials.item]]
      quote = '
1.&nbsp;企业运营管理诊断<br/>
2.&nbsp;组织结构优化（部门、岗位）<br/>
3.&nbsp;薪酬体系和激励机制优化<br/>
4.&nbsp;绩效管理体系优化<br/>
5.&nbsp;薪酬和绩效体系方案落地实施<br/>
6.&nbsp;薪酬和绩效体系方案跟踪辅导<br/>
'
      person = '某金融服务公司薪酬绩效体系重建&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/><span class="subtext">服务周期：6+18</span>'
      img = "person3.jpg"
      alt = "Person3"
        
    [[params.testimonials.item]]
      quote = '
1.&nbsp;团队管理的艺术？<br/>
2.&nbsp;如何配置自己的团队<br/>
3.&nbsp;关于授权<br/>
4.&nbsp;老板应该唱红脸还是黑脸<br/>
5.&nbsp;家国天下？<br/>
6.&nbsp;表扬的艺术<br/>
7.&nbsp;除了钱，没有大事！<br/>
8.&nbsp;发工资差几天发影响不大？<br/>
9.&nbsp;细节决定成败<br/>
'
      person = '某电商公司BOSS私教基础辅导课程&nbsp;&nbsp;<br/><span class="subtext">服务周期：12</span>'
      img = "person1.jpg"
      alt = "Person1"

   
    [[params.testimonials.item]]
      quote = '
1.&nbsp;如何挖掘人才？<br/>
2.&nbsp;中小微企业招不到人怎么办？<br/>
3.&nbsp;现有员工如何激励和绩效管理<br/>
4.&nbsp;劳动风险预防措施<br/>
5.&nbsp;劳动纠纷如何化解<br/>
6.&nbsp;...
'
      person = '某制造业公司人才管理项目&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/><span class="subtext">服务周期：3+9</span>'
      img = "person2.jpg"
      alt = "Person2"


  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000


  # About section
  [params.about]
    enable = true
    title = "核心团队"
    description = "深耕专业、实战为先，我们的团队由在不同行业背景下具有丰富经验的成员组成，以“脚踏实地，用心积累”的精神帮助企业解决问题。"

    [[params.about.item]]
      name = "迦月"
      position = ""
      description = "20年企业管理及人力资源管理实战经验，深耕人力资源管理六大模块。曾在排名前三的国际最具价值互联网企业任HRD，国内第一家纽交所上市的汽车贸易集团HRD，《现代快报》特约撰稿人<br/>"
      img = "F4.png"
      alt = "迦月"
      # social = [
      #   ["icon-twitter", "#"],
      #   ["icon-facebook", "#"],
      #   ["icon-linkedin", "#"]
      # ]

    [[params.about.item]]
      name = "禾雅"
      position = ""
      description = "管理学博士，研究方向为组织发展与人力资源管理，在HR、IR、OB等领域发表论文十余篇，被SCI、SCCI、CSSCI等国内外权威索引收录。参与国家及省部级管理类项目共十余项"
      img = "F2.png"
      alt = "禾雅"

    [[params.about.item]]
      name = "艾文"
      position = ""
      description = "近30年企业管理和营销管理经验，丰富的快消、连锁零售行业营销实战经验。擅长营销团队建设、绩效激励、品牌市场拓展…曾就职于国内500强企业、电器连锁前三强企业<br/>"
      img = "M3.png"
      alt = "艾文"

    [[params.about.item]]
      name = "捷凡"
      position = ""
      description = "绩效管理专家，深耕绩效管理领域近20年。丰富的快消连锁集团、制造业、互联网行业从业经验。擅长绩效薪酬体系的正向激励（BSC/KPI/OKR…）<br/><br/>"
      img = "M4.png"
      alt = "捷凡"

    [[params.about.item]]
      name = "贝迪"
      position = ""
      description = "员工关系管理专家，20多年IT、快消等行业HR从业经验。擅长企业文化建设、员工价值观引导、心理咨询服务、员工冲突管理、员工沟通管理、员工奖惩管理、岗位轮换等"
      img = "M1.png"
      alt = "贝迪"

    [[params.about.item]]
      name = "清境"
      position = ""
      description = "10余年人力资源管理及猎头实战经验，近10年IT与互联网行业HR及猎头从业经验，擅长人岗匹配，结合战略和业务激发人才能动性<br/><br/>"
      img = "F1.png"
      alt = "清境"


  # Contact section
  [params.contact]
    enable = true
    map = false
    form = false
    title = "联系我们"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-location-pin", "南京市江宁区高新园竹山路88号1-3 F"],
        ["icon-envelope", '<a href="mailto:info@hcdz-hr.com">info@hcdz-hr.com</a>'],
        ["icon-globe", '<a href="https://www.hcdz-hr.com/" target="_blank">www.hcdz-hr.com</a>'],
        ["icon-bubbles", "公众号: HR-volunteer"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"


  [params.download]
    details = [
        ["icon-cloud-download", "知识手册下载", "/downloads/【汇诚鼎智】知识手册2018.pdf"],
        ["icon-cloud-download", "调研报告下载", "/downloads/【汇诚鼎智】调研报告KCC17.pdf"],
        ["icon-cloud-download", "宣传册下载", "/downloads/【汇诚鼎智】宣传册-2018.pdf"],
      ]


  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; hcdz-hr.com All Rights Reserved. <br>Created by <a href="http://hcdz-hr.com/" target="_blank">hcdz-hr.com</a>'
    links = [
        ["icon-ghost", "#"],
      ]
